### PR TITLE
#76: Add FindBaseSpell fallback option

### LINKED ISSUE #76: [Bug+Fix] - Non base spells not being recognized
Noticed this on a evoker.

For example;

Dream Breath (Spell ID: 355936) when talented for Font of Magic (Preservation) changes the spell ID to 382614.

I did some testing...
```
IsSpellKnown(382614) # false
IsSpellKnownOrOverridesKnown(382614) # true
C_Spell.PickupSpell(355936) # works
C_Spell.PickupSpell(382614) # doesn't work
FindBaseSpellByID(382614) # 355936
```

Can we add a further fallback option before https://github.com/tg123/myslot/blob/d6006390693534e76455514e7173b0683053771e/Myslot.lua#L754 - something like;

```
                        -- another fallback option - try to get base spell
                        if not GetCursorInfo() then
                            local baseSpellId = FindBaseSpellByID(index)
                            if baseSpellId then
                                PickupSpell(baseSpellId)
                            end
                        end
```

I tested this locally and it works :)

### PR DESCRIPTION
**Pull request by hewozuoai**
Fixes #76.

### CODE REVIEW

File: Myslot.lua [hunk 1]
```diff
@@ -752,6 +752,14 @@ function MySlot:RecoverData(msg, opt)
                             end
                         end
 
+                        -- another fallback option - try to get base spell
+                        if not GetCursorInfo() then
```
Comment (tg123) [inline Myslot.lua:756]:
```suggestion
                        if not GetCursorInfo() and FindBaseSpellByID then
```

work with client prior to 10.0


thanks, actually, i do not no this api, what i did, as you can see, is to create a `CreateSpellOverrideMap`

**Review by tg123 — CHANGES_REQUESTED** [review]

File: Myslot.lua (hunk 1 above)
Comment (hewozuoai) [reply Myslot.lua:756]: did you mean to suggest the change above?

Comment (tg123) [reply Myslot.lua:756]: yup, let me know if it looks good to you

Comment (hewozuoai) [reply Myslot.lua:756]: ahh i see what you mean, lgtm ill give it a quick test today

**Review by tg123 — APPROVED** [review]
